/*
恋小语VIP

下载：https://apps.apple.com/dk/app/id1632878609

====================================
[rewrite_local]
^http:\/\/api\.love\.823123\.com\/facades\/account\.show$ url script-response-body https://raw.githubusercontent.com/wf021325/qx/master/js/lxy.js

[mitm]
hostname  = api.love.823123.com
====================================
 */
var n=n||function(v){function l(){if(f){if("function"==typeof f.getRandomValues)try{return f.getRandomValues(new Uint32Array(1))[0]}catch(a){}if("function"==typeof f.Ca)try{return f.Ca(4).Pa()}catch(a){}}throw Error("Native crypto module could not be used to get secure random number.");}var f;if("undefined"!=typeof window&&window.crypto&&(f=window.crypto),"undefined"!=typeof self&&self.crypto&&(f=self.crypto),"undefined"!=typeof globalThis&&globalThis.crypto&&(f=globalThis.crypto),!f&&"undefined"!=
typeof window&&window.msCrypto&&(f=window.msCrypto),!f&&"undefined"!=typeof global&&global.crypto&&(f=global.crypto),!f&&"function"==typeof require)try{f=require("crypto")}catch(a){}var p=Object.create||function(){function a(){}return function(b){var d;return a.prototype=b,d=new a,a.prototype=null,d}}(),u={},h=u.C={},t=h.ka={extend:function(a){var b=p(this);return a&&b.N(a),b.hasOwnProperty("init")&&this.g!==b.g||(b.g=function(){b.ja.g.apply(this,arguments)}),b.g.prototype=b,b.ja=this,b},create:function(){var a=
this.extend();return a.g.apply(a,arguments),a},g:function(){},N:function(a){for(var b in a)a.hasOwnProperty(b)&&(this[b]=a[b]);a.hasOwnProperty("toString")&&(this.toString=a.toString)},clone:function(){return this.g.prototype.extend(this)}},w=h.R=t.extend({g:function(a,b){a=this.j=a||[];this.h=null!=b?b:4*a.length},toString:function(a){return(a||G).stringify(this)},concat:function(a){var b=this.j,d=a.j,c=this.h;a=a.h;if(this.ea(),c%4)for(var e=0;e<a;e++)b[c+e>>>2]|=(d[e>>>2]>>>24-e%4*8&255)<<24-(c+
e)%4*8;else for(e=0;e<a;e+=4)b[c+e>>>2]=d[e>>>2];return this.h+=a,this},ea:function(){var a=this.j,b=this.h;a[b>>>2]&=4294967295<<32-b%4*8;a.length=v.ceil(b/4)},clone:function(){var a=t.clone.call(this);return a.j=this.j.slice(0),a},random:function(a){function b(q){var x=987654321;return function(){var y=((x=36969*(65535&x)+(x>>16)&4294967295)<<16)+(q=18E3*(65535&q)+(q>>16)&4294967295)&4294967295;return y/=4294967296,(y+.5)*(.5<v.random()?1:-1)}}var d,c=[],e=!1;try{l(),e=!0}catch(q){}for(var m,k=
0;k<a;k+=4)e?c.push(l()):(m=987654071*(d=b(4294967296*(m||v.random())))(),c.push(4294967296*d()|0));return new w.g(c,a)}}),z=u.l={},G=z.Ja={stringify:function(a){var b=a.j;a=a.h;for(var d=[],c=0;c<a;c++){var e=b[c>>>2]>>>24-c%4*8&255;d.push((e>>>4).toString(16));d.push((15&e).toString(16))}return d.join("")},parse:function(a){for(var b=a.length,d=[],c=0;c<b;c+=2)d[c>>>3]|=parseInt(a.substr(c,2),16)<<24-c%8*4;return new w.g(d,b/2)}},E=z.Ka={stringify:function(a){var b=a.j;a=a.h;for(var d=[],c=0;c<
a;c++)d.push(String.fromCharCode(b[c>>>2]>>>24-c%4*8&255));return d.join("")},parse:function(a){for(var b=a.length,d=[],c=0;c<b;c++)d[c>>>2]|=(255&a.charCodeAt(c))<<24-c%4*8;return new w.g(d,b)}},C=z.m={stringify:function(a){try{return decodeURIComponent(escape(E.stringify(a)))}catch(b){throw Error("Malformed UTF-8 data");}},parse:function(a){return E.parse(unescape(encodeURIComponent(a)))}},A=h.ma=t.extend({reset:function(){this.o=new w.g},B:function(a){"string"==typeof a&&(a=C.parse(a));this.o.concat(a)},
u:function(a){var b,d=this.o,c=d.j,e=d.h,m=this.blockSize,k=e/(4*m);a=(a?v.ceil(k):v.max((0|k)-this.Z,0))*m;e=v.min(4*a,e);if(a){for(b=0;b<a;b+=m)this.ta(c,b);b=c.splice(0,a);d.h-=e}return new w.g(b,e)},clone:function(){var a=t.clone.call(this);return a.o=this.o.clone(),a},Z:0}),g=(h.Ia=A.extend({i:t.extend(),g:function(a){this.i=this.i.extend(a);this.reset()},reset:function(){A.reset.call(this);this.V()},update:function(a){return this.B(a),this.u(),this},v:function(a){return a&&this.B(a),this.I()},
blockSize:16,T:function(a){return function(b,d){return(new a.g(d)).v(b)}},Oa:function(a){return function(b,d){return(new g.Ha.g(a,d)).v(b)}}}),u.da={});return u}(Math);function r(v){v=n.l.G.parse(v);return n.l.m.stringify(v)}
!function(){var v=n.C.R;n.l.G={stringify:function(l){var f=l.j,p=l.h,u=this.Y;l.ea();l=[];for(var h=0;h<p;h+=3)for(var t=(f[h>>>2]>>>24-h%4*8&255)<<16|(f[h+1>>>2]>>>24-(h+1)%4*8&255)<<8|f[h+2>>>2]>>>24-(h+2)%4*8&255,w=0;4>w&&h+.75*w<p;w++)l.push(u.charAt(t>>>6*(3-w)&63));if(f=u.charAt(64))for(;l.length%4;)l.push(f);return l.join("")},parse:function(l){var f=l.length,p=this.Y,u=this.xa;if(!u){u=this.xa=[];for(var h=0;h<p.length;h++)u[p.charCodeAt(h)]=h}if(p=p.charAt(64))p=l.indexOf(p),-1!==p&&(f=p);
p=[];for(var t=h=0;t<f;t++)t%4&&(p[h>>>2]|=(u[l.charCodeAt(t-1)]<<t%4*2|u[l.charCodeAt(t)]>>>6-t%4*2)<<24-h%4*8,h++);return v.create(p,h)},Y:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/="}}();
n.C.na||function(v){var l=n.C,f=l.ka,p=l.R,u=l.ma,h=n.l,t=(h.m,h.G),w=n.da.Ga,z=l.na=u.extend({i:f.extend(),L:function(a,b){return this.create(this.H,a,b)},K:function(a,b){return this.create(this.ra,a,b)},g:function(a,b,d){this.i=this.i.extend(d);this.ca=a;this.X=b;this.reset()},reset:function(){u.reset.call(this);this.V()},process:function(a){return this.B(a),this.u()},v:function(a){return a&&this.B(a),this.I()},A:4,ha:4,H:1,ra:2,T:function(){return function(a){return{encrypt:function(b,d,c){return("string"==
typeof d?g:A).encrypt(a,b,d,c)},decrypt:function(b,d,c){return("string"==typeof d?g:A).decrypt(a,b,d,c)}}}}()});h=(l.Na=z.extend({I:function(){return this.u(!0)},blockSize:1}),n.mode={});var G=l.Ea=f.extend({L:function(a,b){return this.pa.create(a,b)},K:function(a,b){return this.oa.create(a,b)},g:function(a,b){this.S=a;this.W=b}});h=h.O=function(){function a(d,c,e){var m,k=this.W;k?(m=k,this.W=v):m=this.ba;for(k=0;k<e;k++)d[c+k]^=m[k]}var b=G.extend();return b.pa=b.extend({ia:function(d,c){var e=
this.S,m=e.blockSize;a.call(this,d,c,m);e.Aa(d,c);this.ba=d.slice(c,c+m)}}),b.oa=b.extend({ia:function(d,c){var e=this.S,m=e.blockSize,k=d.slice(c,c+m);e.za(d,c);a.call(this,d,c,m);this.ba=k}}),b}();var E=(n.D={}).P={D:function(a,b){var d=4*b;d-=a.h%d;for(var c=d<<24|d<<16|d<<8|d,e=[],m=0;m<d;m+=4)e.push(c);d=p.create(e,d);a.concat(d)},Da:function(a){a.h-=255&a.j[a.h-1>>>2]}},C=(l.la=z.extend({i:z.i.extend({mode:h,padding:E}),reset:function(){var a;z.reset.call(this);var b=this.i,d=b.iv;b=b.mode;
this.ca==this.H?a=b.L:(a=b.K,this.Z=1);this.s&&this.s.sa==a?this.s.g(this,d&&d.j):(this.s=a.call(b,this,d&&d.j),this.s.sa=a)},ta:function(a,b){this.s.ia(a,b)},I:function(){var a,b=this.i.padding;return this.ca==this.H?(b.D(this.o,this.blockSize),a=this.u(!0)):(a=this.u(!0),b.Da(a)),a},blockSize:4}),l.Fa=f.extend({g:function(a){this.N(a)},toString:function(a){return(a||this.Ba).stringify(this)}}));h=(n.format={}).qa={stringify:function(a){var b=a.J;a=a.salt;return(a?p.create([1398893684,1701076831]).concat(a).concat(b):
b).toString(t)},parse:function(a){var b;a=t.parse(a);var d=a.j;return 1398893684==d[0]&&1701076831==d[1]&&(b=p.create(d.slice(2,4)),d.splice(0,4),a.h-=16),C.create({J:a,salt:b})}};var A=l.Ma=f.extend({i:f.extend({format:h}),encrypt:function(a,b,d,c){c=this.i.extend(c);var e=a.L(d,c);b=e.v(b);e=e.i;return C.create({J:b,key:d,iv:e.iv,algorithm:a,mode:e.mode,padding:e.padding,blockSize:a.blockSize,Ba:c.format})},decrypt:function(a,b,d,c){return c=this.i.extend(c),b=this.aa(b,c.format),a.K(d,c).v(b.J)},
aa:function(a,b){return"string"==typeof a?b.parse(a,this):a}});f=(n.M={}).qa={fa:function(a,b,d,c,e){var m=(c||(c=p.random(8)),e)?w.create({A:b+d,ga:e}).ya(a,c):w.create({A:b+d}).ya(a,c);a=p.create(m.j.slice(b),4*d);return m.h=4*b,C.create({key:m,iv:a,salt:c})}};var g=l.La=A.extend({i:A.i.extend({M:f}),encrypt:function(a,b,d,c){var e=(c=this.i.extend(c)).M.fa(d,a.A,a.ha,c.salt,c.ga);c.iv=e.iv;a=A.encrypt.call(this,a,b,e.key,c);return a.N(e),a},decrypt:function(a,b,d,c){c=this.i.extend(c);b=this.aa(b,
c.format);d=c.M.fa(d,a.A,a.ha,b.salt,c.ga);return c.iv=d.iv,A.decrypt.call(this,a,b,d.key,c)}})}();
(function(){var v=n.C.la,l=n.da,f=[],p=[],u=[],h=[],t=[],w=[],z=[],G=[],E=[],C=[];!function(){for(var g=[],a=0;256>a;a++)g[a]=128>a?a<<1:a<<1^283;var b=0,d=0;for(a=0;256>a;a++){var c=d^d<<1^d<<2^d<<3^d<<4;c=c>>>8^255&c^99;f[b]=c;p[c]=b;var e=g[b],m=g[e],k=g[m],q=257*g[c]^16843008*c;u[b]=q<<24|q>>>8;h[b]=q<<16|q>>>16;t[b]=q<<8|q>>>24;w[b]=q;q=16843009*k^65537*m^257*e^16843008*b;z[c]=q<<24|q>>>8;G[c]=q<<16|q>>>16;E[c]=q<<8|q>>>24;C[c]=q;b?(b=e^g[g[g[k^e]]],d^=g[g[d]]):b=d=1}}();var A=[0,1,2,4,8,16,
32,64,128,27,54];l=l.F=v.extend({V:function(){if(!this.$||this.va!==this.X){var g=this.va=this.X,a=g.j,b=g.h/4;g=4*((this.$=b+6)+1);for(var d=this.wa=[],c=0;c<g;c++)if(c<b)d[c]=a[c];else{var e=d[c-1];c%b?6<b&&4==c%b&&(e=f[e>>>24]<<24|f[e>>>16&255]<<16|f[e>>>8&255]<<8|f[255&e]):(e=f[(e=e<<8|e>>>24)>>>24]<<24|f[e>>>16&255]<<16|f[e>>>8&255]<<8|f[255&e],e^=A[c/b|0]<<24);d[c]=d[c-b]^e}a=this.ua=[];for(b=0;b<g;b++)c=g-b,e=b%4?d[c]:d[c-4],a[b]=4>b||4>=c?e:z[f[e>>>24]]^G[f[e>>>16&255]]^E[f[e>>>8&255]]^C[f[255&
e]]}},Aa:function(g,a){this.U(g,a,this.wa,u,h,t,w,f)},za:function(g,a){var b=g[a+1];g[a+1]=g[a+3];g[a+3]=b;this.U(g,a,this.ua,z,G,E,C,p);b=g[a+1];g[a+1]=g[a+3];g[a+3]=b},U:function(g,a,b,d,c,e,m,k){for(var q=this.$,x=g[a]^b[0],y=g[a+1]^b[1],D=g[a+2]^b[2],B=g[a+3]^b[3],F=4,Q=1;Q<q;Q++){var H=d[x>>>24]^c[y>>>16&255]^e[D>>>8&255]^m[255&B]^b[F++],I=d[y>>>24]^c[D>>>16&255]^e[B>>>8&255]^m[255&x]^b[F++],J=d[D>>>24]^c[B>>>16&255]^e[x>>>8&255]^m[255&y]^b[F++];B=d[B>>>24]^c[x>>>16&255]^e[y>>>8&255]^m[255&D]^
b[F++];x=H;y=I;D=J}H=(k[x>>>24]<<24|k[y>>>16&255]<<16|k[D>>>8&255]<<8|k[255&B])^b[F++];I=(k[y>>>24]<<24|k[D>>>16&255]<<16|k[B>>>8&255]<<8|k[255&x])^b[F++];J=(k[D>>>24]<<24|k[B>>>16&255]<<16|k[x>>>8&255]<<8|k[255&y])^b[F++];B=(k[B>>>24]<<24|k[x>>>16&255]<<16|k[y>>>8&255]<<8|k[255&D])^b[F++];g[a]=H;g[a+1]=I;g[a+2]=J;g[a+3]=B},A:8});n.F=v.T(l)})();var K=$response.body,L=JSON.parse(K),M=r(L.data);L=JSON.parse(M);var N=L.iv,O=r(N),P=L.value,R=P,S="lX4uSSGqztP3vQ7K";S=n.l.m.parse(S);
word=n.F.decrypt(R,S,{iv:n.l.m.parse(O),mode:n.mode.O,padding:n.D.P}).toString(n.l.m);L={};L=JSON.parse(word);L.data.guest=!1;L.data.vip_expired_at="3742732800";L.data.perpetual_vip=!0;L.data.vip=!0;L.data.nickname="\u82cd\u4e95\u7070\u7070";L.data.id=L.data.identifyCode=10086;L.data.avatar_url=L.data.profilePhoto_url="https://love-helper.oss-cn-hangzhou.aliyuncs.com/images/2023/09/06/n33C7GybsrML8UHOioWnsV2ERLGjLAnysrqpmLTT.jpg";word=JSON.stringify(L);var T="lX4uSSGqztP3vQ7K",U=n.l.m.parse(word);
T=n.l.m.parse(T);P=n.F.encrypt(U,T,{iv:n.l.m.parse(O),mode:n.mode.O,padding:n.D.P}).toString();L={};L.iv=N;L.value=P;M=JSON.stringify(L);var V=L={},W,X=n.l.m.parse(M);W=n.l.G.stringify(X);V.data=W;K=JSON.stringify(L);$done({K});